window_width: 640
window_height: 480
row_count: 15
col_count: 20
frame_rate: 8
delay_before_start: 3

teams:
    -   name: "Red Team"
        tanks:
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [0, 0]
                color: [255, 0, 0]
                
            -   bot_path: "examples/bots/defender.yaml"
                initial_position: [1, 1]
                color: [205, 0, 0]
                
            -   bot_path: "examples/bots/defender.yaml"
                initial_position: [2, 2]
                color: [155, 0, 0]
                
    -   name: "Blue Team"
        tanks:
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [14, 19]
                color: [0, 0, 255]
                
            -   bot_path: "examples/bots/attacker.yaml"
                initial_position: [13, 18]
                color: [0, 0, 205]
                
            -   bot_path: "examples/bots/attacker.yaml"
                initial_position: [12, 17]
                color: [0, 0, 155]
