window_width: 640
window_height: 480
row_count: 15
col_count: 20
frame_rate: 40
delay_before_start: 3

### TODO: ambil solo

teams:
    -   name: "Red Team"
        tanks:
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [1, 2]
                color: [255, 0, 0]
                
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [2, 3]
                color: [205, 0, 0]
                
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [3, 4]
                color: [155, 0, 0]
                
    -   name: "Blue Team"
        tanks:
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [5, 2]
                color: [0, 0, 255]
                
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [6, 3]
                color: [0, 0, 205]
                
            -   bot_path: "examples/bots/guard.yaml"
                initial_position: [7, 4]
                color: [0, 0, 155]
